# Site settings
title: Rubens Fernando
tagline: 'Design, desenvolvimento e infografia'
email: ola@rubensfernando.com
permantlink: /:categories/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Sou designer e desenvolvedor no jornal <a href='http://www.folha.com.br'>Folha de S.Paulo</a>, na editoria de Arte, desenvolvendo infográficos e outras histórias visuais.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubensfernando.com" # the base hostname & protocol for your site
twitter_username: rubensfernando
github_username:  rubensfernando
linkedin_username:  rubensfernando
lastfm_username: rubfernando

# Build settings
markdown: kramdown

exclude: [
  'README.md',
  'package.json',
  'Gruntfile.js',
  'node_modules',
  'Gemfile*',
  'assets/sass',
  'bower.json',
  'tasks'
]

# Move build
destination: ../rubensfernando.github.io/

# Portfolio plugin
portfolio_root: /trabalhos
portfolio_path: /assets/images/pages/trabalhos
portfolio_img_root: /images/pages/trabalhos
